import {Roboto} from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import AppProvider from "@/app/AppProvider";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin", "cyrillic"],
    weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
      <html lang="uk">
          <body className={`${roboto.variable} antialiased`}>
              <AppProvider>
                  <div className="flex h-full w-full row">
                      <SideBar/>
                      <div className="flex-1 page p-2">
                          {children}
                      </div>
                  </div>
              </AppProvider>
          </body>
      </html>
  );
}
